// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: book/v1/book.proto
// Protobuf Java Version: 4.31.1

package org.noxhalley.contracts.book.v1;

@com.google.protobuf.Generated
public final class BookOuterClass {
  private BookOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      BookOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BookOrBuilder extends
      // @@protoc_insertion_point(interface_extends:book.v1.Book)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string publisher = 3 [json_name = "publisher"];</code>
     * @return The publisher.
     */
    java.lang.String getPublisher();
    /**
     * <code>string publisher = 3 [json_name = "publisher"];</code>
     * @return The bytes for publisher.
     */
    com.google.protobuf.ByteString
        getPublisherBytes();
  }
  /**
   * Protobuf type {@code book.v1.Book}
   */
  public static final class Book extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:book.v1.Book)
      BookOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        Book.class.getName());
    }
    // Use Book.newBuilder() to construct.
    private Book(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Book() {
      name_ = "";
      publisher_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.noxhalley.contracts.book.v1.BookOuterClass.internal_static_book_v1_Book_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.noxhalley.contracts.book.v1.BookOuterClass.internal_static_book_v1_Book_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.noxhalley.contracts.book.v1.BookOuterClass.Book.class, org.noxhalley.contracts.book.v1.BookOuterClass.Book.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PUBLISHER_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object publisher_ = "";
    /**
     * <code>string publisher = 3 [json_name = "publisher"];</code>
     * @return The publisher.
     */
    @java.lang.Override
    public java.lang.String getPublisher() {
      java.lang.Object ref = publisher_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        publisher_ = s;
        return s;
      }
    }
    /**
     * <code>string publisher = 3 [json_name = "publisher"];</code>
     * @return The bytes for publisher.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPublisherBytes() {
      java.lang.Object ref = publisher_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        publisher_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(publisher_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, publisher_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(publisher_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, publisher_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.noxhalley.contracts.book.v1.BookOuterClass.Book)) {
        return super.equals(obj);
      }
      org.noxhalley.contracts.book.v1.BookOuterClass.Book other = (org.noxhalley.contracts.book.v1.BookOuterClass.Book) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getPublisher()
          .equals(other.getPublisher())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + PUBLISHER_FIELD_NUMBER;
      hash = (53 * hash) + getPublisher().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.noxhalley.contracts.book.v1.BookOuterClass.Book parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.Book parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.Book parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.Book parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.Book parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.Book parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.Book parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.Book parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.noxhalley.contracts.book.v1.BookOuterClass.Book parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.noxhalley.contracts.book.v1.BookOuterClass.Book parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.Book parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.Book parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.noxhalley.contracts.book.v1.BookOuterClass.Book prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code book.v1.Book}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:book.v1.Book)
        org.noxhalley.contracts.book.v1.BookOuterClass.BookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.noxhalley.contracts.book.v1.BookOuterClass.internal_static_book_v1_Book_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.noxhalley.contracts.book.v1.BookOuterClass.internal_static_book_v1_Book_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.noxhalley.contracts.book.v1.BookOuterClass.Book.class, org.noxhalley.contracts.book.v1.BookOuterClass.Book.Builder.class);
      }

      // Construct using org.noxhalley.contracts.book.v1.BookOuterClass.Book.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        name_ = "";
        publisher_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.noxhalley.contracts.book.v1.BookOuterClass.internal_static_book_v1_Book_descriptor;
      }

      @java.lang.Override
      public org.noxhalley.contracts.book.v1.BookOuterClass.Book getDefaultInstanceForType() {
        return org.noxhalley.contracts.book.v1.BookOuterClass.Book.getDefaultInstance();
      }

      @java.lang.Override
      public org.noxhalley.contracts.book.v1.BookOuterClass.Book build() {
        org.noxhalley.contracts.book.v1.BookOuterClass.Book result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.noxhalley.contracts.book.v1.BookOuterClass.Book buildPartial() {
        org.noxhalley.contracts.book.v1.BookOuterClass.Book result = new org.noxhalley.contracts.book.v1.BookOuterClass.Book(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.noxhalley.contracts.book.v1.BookOuterClass.Book result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.publisher_ = publisher_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.noxhalley.contracts.book.v1.BookOuterClass.Book) {
          return mergeFrom((org.noxhalley.contracts.book.v1.BookOuterClass.Book)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.noxhalley.contracts.book.v1.BookOuterClass.Book other) {
        if (other == org.noxhalley.contracts.book.v1.BookOuterClass.Book.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getPublisher().isEmpty()) {
          publisher_ = other.publisher_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                publisher_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1 [json_name = "id"];</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1 [json_name = "id"];</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1 [json_name = "id"];</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2 [json_name = "name"];</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2 [json_name = "name"];</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2 [json_name = "name"];</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2 [json_name = "name"];</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2 [json_name = "name"];</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object publisher_ = "";
      /**
       * <code>string publisher = 3 [json_name = "publisher"];</code>
       * @return The publisher.
       */
      public java.lang.String getPublisher() {
        java.lang.Object ref = publisher_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          publisher_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string publisher = 3 [json_name = "publisher"];</code>
       * @return The bytes for publisher.
       */
      public com.google.protobuf.ByteString
          getPublisherBytes() {
        java.lang.Object ref = publisher_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          publisher_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string publisher = 3 [json_name = "publisher"];</code>
       * @param value The publisher to set.
       * @return This builder for chaining.
       */
      public Builder setPublisher(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        publisher_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string publisher = 3 [json_name = "publisher"];</code>
       * @return This builder for chaining.
       */
      public Builder clearPublisher() {
        publisher_ = getDefaultInstance().getPublisher();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string publisher = 3 [json_name = "publisher"];</code>
       * @param value The bytes for publisher to set.
       * @return This builder for chaining.
       */
      public Builder setPublisherBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        publisher_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:book.v1.Book)
    }

    // @@protoc_insertion_point(class_scope:book.v1.Book)
    private static final org.noxhalley.contracts.book.v1.BookOuterClass.Book DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.noxhalley.contracts.book.v1.BookOuterClass.Book();
    }

    public static org.noxhalley.contracts.book.v1.BookOuterClass.Book getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Book>
        PARSER = new com.google.protobuf.AbstractParser<Book>() {
      @java.lang.Override
      public Book parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Book> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Book> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.noxhalley.contracts.book.v1.BookOuterClass.Book getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetBookRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:book.v1.GetBookRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    int getId();
  }
  /**
   * Protobuf type {@code book.v1.GetBookRequest}
   */
  public static final class GetBookRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:book.v1.GetBookRequest)
      GetBookRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        GetBookRequest.class.getName());
    }
    // Use GetBookRequest.newBuilder() to construct.
    private GetBookRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetBookRequest() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.noxhalley.contracts.book.v1.BookOuterClass.internal_static_book_v1_GetBookRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.noxhalley.contracts.book.v1.BookOuterClass.internal_static_book_v1_GetBookRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest.class, org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest)) {
        return super.equals(obj);
      }
      org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest other = (org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest) obj;

      if (getId()
          != other.getId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code book.v1.GetBookRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:book.v1.GetBookRequest)
        org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.noxhalley.contracts.book.v1.BookOuterClass.internal_static_book_v1_GetBookRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.noxhalley.contracts.book.v1.BookOuterClass.internal_static_book_v1_GetBookRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest.class, org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest.Builder.class);
      }

      // Construct using org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.noxhalley.contracts.book.v1.BookOuterClass.internal_static_book_v1_GetBookRequest_descriptor;
      }

      @java.lang.Override
      public org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest getDefaultInstanceForType() {
        return org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest build() {
        org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest buildPartial() {
        org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest result = new org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest) {
          return mergeFrom((org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest other) {
        if (other == org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1 [json_name = "id"];</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1 [json_name = "id"];</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1 [json_name = "id"];</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:book.v1.GetBookRequest)
    }

    // @@protoc_insertion_point(class_scope:book.v1.GetBookRequest)
    private static final org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest();
    }

    public static org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetBookRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetBookRequest>() {
      @java.lang.Override
      public GetBookRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetBookRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetBookRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.noxhalley.contracts.book.v1.BookOuterClass.GetBookRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetBookResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:book.v1.GetBookResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.book.v1.Book book = 1 [json_name = "book"];</code>
     * @return Whether the book field is set.
     */
    boolean hasBook();
    /**
     * <code>.book.v1.Book book = 1 [json_name = "book"];</code>
     * @return The book.
     */
    org.noxhalley.contracts.book.v1.BookOuterClass.Book getBook();
    /**
     * <code>.book.v1.Book book = 1 [json_name = "book"];</code>
     */
    org.noxhalley.contracts.book.v1.BookOuterClass.BookOrBuilder getBookOrBuilder();
  }
  /**
   * Protobuf type {@code book.v1.GetBookResponse}
   */
  public static final class GetBookResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:book.v1.GetBookResponse)
      GetBookResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        GetBookResponse.class.getName());
    }
    // Use GetBookResponse.newBuilder() to construct.
    private GetBookResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetBookResponse() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.noxhalley.contracts.book.v1.BookOuterClass.internal_static_book_v1_GetBookResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.noxhalley.contracts.book.v1.BookOuterClass.internal_static_book_v1_GetBookResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse.class, org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse.Builder.class);
    }

    private int bitField0_;
    public static final int BOOK_FIELD_NUMBER = 1;
    private org.noxhalley.contracts.book.v1.BookOuterClass.Book book_;
    /**
     * <code>.book.v1.Book book = 1 [json_name = "book"];</code>
     * @return Whether the book field is set.
     */
    @java.lang.Override
    public boolean hasBook() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.book.v1.Book book = 1 [json_name = "book"];</code>
     * @return The book.
     */
    @java.lang.Override
    public org.noxhalley.contracts.book.v1.BookOuterClass.Book getBook() {
      return book_ == null ? org.noxhalley.contracts.book.v1.BookOuterClass.Book.getDefaultInstance() : book_;
    }
    /**
     * <code>.book.v1.Book book = 1 [json_name = "book"];</code>
     */
    @java.lang.Override
    public org.noxhalley.contracts.book.v1.BookOuterClass.BookOrBuilder getBookOrBuilder() {
      return book_ == null ? org.noxhalley.contracts.book.v1.BookOuterClass.Book.getDefaultInstance() : book_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getBook());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBook());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse)) {
        return super.equals(obj);
      }
      org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse other = (org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse) obj;

      if (hasBook() != other.hasBook()) return false;
      if (hasBook()) {
        if (!getBook()
            .equals(other.getBook())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBook()) {
        hash = (37 * hash) + BOOK_FIELD_NUMBER;
        hash = (53 * hash) + getBook().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code book.v1.GetBookResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:book.v1.GetBookResponse)
        org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.noxhalley.contracts.book.v1.BookOuterClass.internal_static_book_v1_GetBookResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.noxhalley.contracts.book.v1.BookOuterClass.internal_static_book_v1_GetBookResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse.class, org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse.Builder.class);
      }

      // Construct using org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetBookFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        book_ = null;
        if (bookBuilder_ != null) {
          bookBuilder_.dispose();
          bookBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.noxhalley.contracts.book.v1.BookOuterClass.internal_static_book_v1_GetBookResponse_descriptor;
      }

      @java.lang.Override
      public org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse getDefaultInstanceForType() {
        return org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse build() {
        org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse buildPartial() {
        org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse result = new org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.book_ = bookBuilder_ == null
              ? book_
              : bookBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse) {
          return mergeFrom((org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse other) {
        if (other == org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse.getDefaultInstance()) return this;
        if (other.hasBook()) {
          mergeBook(other.getBook());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    internalGetBookFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private org.noxhalley.contracts.book.v1.BookOuterClass.Book book_;
      private com.google.protobuf.SingleFieldBuilder<
          org.noxhalley.contracts.book.v1.BookOuterClass.Book, org.noxhalley.contracts.book.v1.BookOuterClass.Book.Builder, org.noxhalley.contracts.book.v1.BookOuterClass.BookOrBuilder> bookBuilder_;
      /**
       * <code>.book.v1.Book book = 1 [json_name = "book"];</code>
       * @return Whether the book field is set.
       */
      public boolean hasBook() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.book.v1.Book book = 1 [json_name = "book"];</code>
       * @return The book.
       */
      public org.noxhalley.contracts.book.v1.BookOuterClass.Book getBook() {
        if (bookBuilder_ == null) {
          return book_ == null ? org.noxhalley.contracts.book.v1.BookOuterClass.Book.getDefaultInstance() : book_;
        } else {
          return bookBuilder_.getMessage();
        }
      }
      /**
       * <code>.book.v1.Book book = 1 [json_name = "book"];</code>
       */
      public Builder setBook(org.noxhalley.contracts.book.v1.BookOuterClass.Book value) {
        if (bookBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          book_ = value;
        } else {
          bookBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.book.v1.Book book = 1 [json_name = "book"];</code>
       */
      public Builder setBook(
          org.noxhalley.contracts.book.v1.BookOuterClass.Book.Builder builderForValue) {
        if (bookBuilder_ == null) {
          book_ = builderForValue.build();
        } else {
          bookBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.book.v1.Book book = 1 [json_name = "book"];</code>
       */
      public Builder mergeBook(org.noxhalley.contracts.book.v1.BookOuterClass.Book value) {
        if (bookBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            book_ != null &&
            book_ != org.noxhalley.contracts.book.v1.BookOuterClass.Book.getDefaultInstance()) {
            getBookBuilder().mergeFrom(value);
          } else {
            book_ = value;
          }
        } else {
          bookBuilder_.mergeFrom(value);
        }
        if (book_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.book.v1.Book book = 1 [json_name = "book"];</code>
       */
      public Builder clearBook() {
        bitField0_ = (bitField0_ & ~0x00000001);
        book_ = null;
        if (bookBuilder_ != null) {
          bookBuilder_.dispose();
          bookBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.book.v1.Book book = 1 [json_name = "book"];</code>
       */
      public org.noxhalley.contracts.book.v1.BookOuterClass.Book.Builder getBookBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return internalGetBookFieldBuilder().getBuilder();
      }
      /**
       * <code>.book.v1.Book book = 1 [json_name = "book"];</code>
       */
      public org.noxhalley.contracts.book.v1.BookOuterClass.BookOrBuilder getBookOrBuilder() {
        if (bookBuilder_ != null) {
          return bookBuilder_.getMessageOrBuilder();
        } else {
          return book_ == null ?
              org.noxhalley.contracts.book.v1.BookOuterClass.Book.getDefaultInstance() : book_;
        }
      }
      /**
       * <code>.book.v1.Book book = 1 [json_name = "book"];</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.noxhalley.contracts.book.v1.BookOuterClass.Book, org.noxhalley.contracts.book.v1.BookOuterClass.Book.Builder, org.noxhalley.contracts.book.v1.BookOuterClass.BookOrBuilder> 
          internalGetBookFieldBuilder() {
        if (bookBuilder_ == null) {
          bookBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.noxhalley.contracts.book.v1.BookOuterClass.Book, org.noxhalley.contracts.book.v1.BookOuterClass.Book.Builder, org.noxhalley.contracts.book.v1.BookOuterClass.BookOrBuilder>(
                  getBook(),
                  getParentForChildren(),
                  isClean());
          book_ = null;
        }
        return bookBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:book.v1.GetBookResponse)
    }

    // @@protoc_insertion_point(class_scope:book.v1.GetBookResponse)
    private static final org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse();
    }

    public static org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetBookResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetBookResponse>() {
      @java.lang.Override
      public GetBookResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetBookResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetBookResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.noxhalley.contracts.book.v1.BookOuterClass.GetBookResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ListBooksResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:book.v1.ListBooksResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .book.v1.Book books = 1 [json_name = "books"];</code>
     */
    java.util.List<org.noxhalley.contracts.book.v1.BookOuterClass.Book> 
        getBooksList();
    /**
     * <code>repeated .book.v1.Book books = 1 [json_name = "books"];</code>
     */
    org.noxhalley.contracts.book.v1.BookOuterClass.Book getBooks(int index);
    /**
     * <code>repeated .book.v1.Book books = 1 [json_name = "books"];</code>
     */
    int getBooksCount();
    /**
     * <code>repeated .book.v1.Book books = 1 [json_name = "books"];</code>
     */
    java.util.List<? extends org.noxhalley.contracts.book.v1.BookOuterClass.BookOrBuilder> 
        getBooksOrBuilderList();
    /**
     * <code>repeated .book.v1.Book books = 1 [json_name = "books"];</code>
     */
    org.noxhalley.contracts.book.v1.BookOuterClass.BookOrBuilder getBooksOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code book.v1.ListBooksResponse}
   */
  public static final class ListBooksResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:book.v1.ListBooksResponse)
      ListBooksResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        ListBooksResponse.class.getName());
    }
    // Use ListBooksResponse.newBuilder() to construct.
    private ListBooksResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ListBooksResponse() {
      books_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.noxhalley.contracts.book.v1.BookOuterClass.internal_static_book_v1_ListBooksResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.noxhalley.contracts.book.v1.BookOuterClass.internal_static_book_v1_ListBooksResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse.class, org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse.Builder.class);
    }

    public static final int BOOKS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<org.noxhalley.contracts.book.v1.BookOuterClass.Book> books_;
    /**
     * <code>repeated .book.v1.Book books = 1 [json_name = "books"];</code>
     */
    @java.lang.Override
    public java.util.List<org.noxhalley.contracts.book.v1.BookOuterClass.Book> getBooksList() {
      return books_;
    }
    /**
     * <code>repeated .book.v1.Book books = 1 [json_name = "books"];</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.noxhalley.contracts.book.v1.BookOuterClass.BookOrBuilder> 
        getBooksOrBuilderList() {
      return books_;
    }
    /**
     * <code>repeated .book.v1.Book books = 1 [json_name = "books"];</code>
     */
    @java.lang.Override
    public int getBooksCount() {
      return books_.size();
    }
    /**
     * <code>repeated .book.v1.Book books = 1 [json_name = "books"];</code>
     */
    @java.lang.Override
    public org.noxhalley.contracts.book.v1.BookOuterClass.Book getBooks(int index) {
      return books_.get(index);
    }
    /**
     * <code>repeated .book.v1.Book books = 1 [json_name = "books"];</code>
     */
    @java.lang.Override
    public org.noxhalley.contracts.book.v1.BookOuterClass.BookOrBuilder getBooksOrBuilder(
        int index) {
      return books_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < books_.size(); i++) {
        output.writeMessage(1, books_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < books_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, books_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse)) {
        return super.equals(obj);
      }
      org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse other = (org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse) obj;

      if (!getBooksList()
          .equals(other.getBooksList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getBooksCount() > 0) {
        hash = (37 * hash) + BOOKS_FIELD_NUMBER;
        hash = (53 * hash) + getBooksList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code book.v1.ListBooksResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:book.v1.ListBooksResponse)
        org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.noxhalley.contracts.book.v1.BookOuterClass.internal_static_book_v1_ListBooksResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.noxhalley.contracts.book.v1.BookOuterClass.internal_static_book_v1_ListBooksResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse.class, org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse.Builder.class);
      }

      // Construct using org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (booksBuilder_ == null) {
          books_ = java.util.Collections.emptyList();
        } else {
          books_ = null;
          booksBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.noxhalley.contracts.book.v1.BookOuterClass.internal_static_book_v1_ListBooksResponse_descriptor;
      }

      @java.lang.Override
      public org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse getDefaultInstanceForType() {
        return org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse build() {
        org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse buildPartial() {
        org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse result = new org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse result) {
        if (booksBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            books_ = java.util.Collections.unmodifiableList(books_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.books_ = books_;
        } else {
          result.books_ = booksBuilder_.build();
        }
      }

      private void buildPartial0(org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse) {
          return mergeFrom((org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse other) {
        if (other == org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse.getDefaultInstance()) return this;
        if (booksBuilder_ == null) {
          if (!other.books_.isEmpty()) {
            if (books_.isEmpty()) {
              books_ = other.books_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBooksIsMutable();
              books_.addAll(other.books_);
            }
            onChanged();
          }
        } else {
          if (!other.books_.isEmpty()) {
            if (booksBuilder_.isEmpty()) {
              booksBuilder_.dispose();
              booksBuilder_ = null;
              books_ = other.books_;
              bitField0_ = (bitField0_ & ~0x00000001);
              booksBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetBooksFieldBuilder() : null;
            } else {
              booksBuilder_.addAllMessages(other.books_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                org.noxhalley.contracts.book.v1.BookOuterClass.Book m =
                    input.readMessage(
                        org.noxhalley.contracts.book.v1.BookOuterClass.Book.parser(),
                        extensionRegistry);
                if (booksBuilder_ == null) {
                  ensureBooksIsMutable();
                  books_.add(m);
                } else {
                  booksBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<org.noxhalley.contracts.book.v1.BookOuterClass.Book> books_ =
        java.util.Collections.emptyList();
      private void ensureBooksIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          books_ = new java.util.ArrayList<org.noxhalley.contracts.book.v1.BookOuterClass.Book>(books_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.noxhalley.contracts.book.v1.BookOuterClass.Book, org.noxhalley.contracts.book.v1.BookOuterClass.Book.Builder, org.noxhalley.contracts.book.v1.BookOuterClass.BookOrBuilder> booksBuilder_;

      /**
       * <code>repeated .book.v1.Book books = 1 [json_name = "books"];</code>
       */
      public java.util.List<org.noxhalley.contracts.book.v1.BookOuterClass.Book> getBooksList() {
        if (booksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(books_);
        } else {
          return booksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .book.v1.Book books = 1 [json_name = "books"];</code>
       */
      public int getBooksCount() {
        if (booksBuilder_ == null) {
          return books_.size();
        } else {
          return booksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .book.v1.Book books = 1 [json_name = "books"];</code>
       */
      public org.noxhalley.contracts.book.v1.BookOuterClass.Book getBooks(int index) {
        if (booksBuilder_ == null) {
          return books_.get(index);
        } else {
          return booksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .book.v1.Book books = 1 [json_name = "books"];</code>
       */
      public Builder setBooks(
          int index, org.noxhalley.contracts.book.v1.BookOuterClass.Book value) {
        if (booksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBooksIsMutable();
          books_.set(index, value);
          onChanged();
        } else {
          booksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .book.v1.Book books = 1 [json_name = "books"];</code>
       */
      public Builder setBooks(
          int index, org.noxhalley.contracts.book.v1.BookOuterClass.Book.Builder builderForValue) {
        if (booksBuilder_ == null) {
          ensureBooksIsMutable();
          books_.set(index, builderForValue.build());
          onChanged();
        } else {
          booksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .book.v1.Book books = 1 [json_name = "books"];</code>
       */
      public Builder addBooks(org.noxhalley.contracts.book.v1.BookOuterClass.Book value) {
        if (booksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBooksIsMutable();
          books_.add(value);
          onChanged();
        } else {
          booksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .book.v1.Book books = 1 [json_name = "books"];</code>
       */
      public Builder addBooks(
          int index, org.noxhalley.contracts.book.v1.BookOuterClass.Book value) {
        if (booksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBooksIsMutable();
          books_.add(index, value);
          onChanged();
        } else {
          booksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .book.v1.Book books = 1 [json_name = "books"];</code>
       */
      public Builder addBooks(
          org.noxhalley.contracts.book.v1.BookOuterClass.Book.Builder builderForValue) {
        if (booksBuilder_ == null) {
          ensureBooksIsMutable();
          books_.add(builderForValue.build());
          onChanged();
        } else {
          booksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .book.v1.Book books = 1 [json_name = "books"];</code>
       */
      public Builder addBooks(
          int index, org.noxhalley.contracts.book.v1.BookOuterClass.Book.Builder builderForValue) {
        if (booksBuilder_ == null) {
          ensureBooksIsMutable();
          books_.add(index, builderForValue.build());
          onChanged();
        } else {
          booksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .book.v1.Book books = 1 [json_name = "books"];</code>
       */
      public Builder addAllBooks(
          java.lang.Iterable<? extends org.noxhalley.contracts.book.v1.BookOuterClass.Book> values) {
        if (booksBuilder_ == null) {
          ensureBooksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, books_);
          onChanged();
        } else {
          booksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .book.v1.Book books = 1 [json_name = "books"];</code>
       */
      public Builder clearBooks() {
        if (booksBuilder_ == null) {
          books_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          booksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .book.v1.Book books = 1 [json_name = "books"];</code>
       */
      public Builder removeBooks(int index) {
        if (booksBuilder_ == null) {
          ensureBooksIsMutable();
          books_.remove(index);
          onChanged();
        } else {
          booksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .book.v1.Book books = 1 [json_name = "books"];</code>
       */
      public org.noxhalley.contracts.book.v1.BookOuterClass.Book.Builder getBooksBuilder(
          int index) {
        return internalGetBooksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .book.v1.Book books = 1 [json_name = "books"];</code>
       */
      public org.noxhalley.contracts.book.v1.BookOuterClass.BookOrBuilder getBooksOrBuilder(
          int index) {
        if (booksBuilder_ == null) {
          return books_.get(index);  } else {
          return booksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .book.v1.Book books = 1 [json_name = "books"];</code>
       */
      public java.util.List<? extends org.noxhalley.contracts.book.v1.BookOuterClass.BookOrBuilder> 
           getBooksOrBuilderList() {
        if (booksBuilder_ != null) {
          return booksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(books_);
        }
      }
      /**
       * <code>repeated .book.v1.Book books = 1 [json_name = "books"];</code>
       */
      public org.noxhalley.contracts.book.v1.BookOuterClass.Book.Builder addBooksBuilder() {
        return internalGetBooksFieldBuilder().addBuilder(
            org.noxhalley.contracts.book.v1.BookOuterClass.Book.getDefaultInstance());
      }
      /**
       * <code>repeated .book.v1.Book books = 1 [json_name = "books"];</code>
       */
      public org.noxhalley.contracts.book.v1.BookOuterClass.Book.Builder addBooksBuilder(
          int index) {
        return internalGetBooksFieldBuilder().addBuilder(
            index, org.noxhalley.contracts.book.v1.BookOuterClass.Book.getDefaultInstance());
      }
      /**
       * <code>repeated .book.v1.Book books = 1 [json_name = "books"];</code>
       */
      public java.util.List<org.noxhalley.contracts.book.v1.BookOuterClass.Book.Builder> 
           getBooksBuilderList() {
        return internalGetBooksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.noxhalley.contracts.book.v1.BookOuterClass.Book, org.noxhalley.contracts.book.v1.BookOuterClass.Book.Builder, org.noxhalley.contracts.book.v1.BookOuterClass.BookOrBuilder> 
          internalGetBooksFieldBuilder() {
        if (booksBuilder_ == null) {
          booksBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.noxhalley.contracts.book.v1.BookOuterClass.Book, org.noxhalley.contracts.book.v1.BookOuterClass.Book.Builder, org.noxhalley.contracts.book.v1.BookOuterClass.BookOrBuilder>(
                  books_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          books_ = null;
        }
        return booksBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:book.v1.ListBooksResponse)
    }

    // @@protoc_insertion_point(class_scope:book.v1.ListBooksResponse)
    private static final org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse();
    }

    public static org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ListBooksResponse>
        PARSER = new com.google.protobuf.AbstractParser<ListBooksResponse>() {
      @java.lang.Override
      public ListBooksResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ListBooksResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ListBooksResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.noxhalley.contracts.book.v1.BookOuterClass.ListBooksResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_book_v1_Book_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_book_v1_Book_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_book_v1_GetBookRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_book_v1_GetBookRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_book_v1_GetBookResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_book_v1_GetBookResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_book_v1_ListBooksResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_book_v1_ListBooksResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022book/v1/book.proto\022\007book.v1\032\033google/pr" +
      "otobuf/empty.proto\"H\n\004Book\022\016\n\002id\030\001 \001(\005R\002" +
      "id\022\022\n\004name\030\002 \001(\tR\004name\022\034\n\tpublisher\030\003 \001(" +
      "\tR\tpublisher\" \n\016GetBookRequest\022\016\n\002id\030\001 \001" +
      "(\005R\002id\"4\n\017GetBookResponse\022!\n\004book\030\001 \001(\0132" +
      "\r.book.v1.BookR\004book\"8\n\021ListBooksRespons" +
      "e\022#\n\005books\030\001 \003(\0132\r.book.v1.BookR\005books2\220" +
      "\001\n\013BookService\022>\n\007GetBook\022\027.book.v1.GetB" +
      "ookRequest\032\030.book.v1.GetBookResponse\"\000\022A" +
      "\n\tListBooks\022\026.google.protobuf.Empty\032\032.bo" +
      "ok.v1.ListBooksResponse\"\000BW\n\037org.noxhall" +
      "ey.contracts.book.v1Z4github.com/noxhall" +
      "ey/contracts/gen/go/book/v1;bookv1b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_book_v1_Book_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_book_v1_Book_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_book_v1_Book_descriptor,
        new java.lang.String[] { "Id", "Name", "Publisher", });
    internal_static_book_v1_GetBookRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_book_v1_GetBookRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_book_v1_GetBookRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_book_v1_GetBookResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_book_v1_GetBookResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_book_v1_GetBookResponse_descriptor,
        new java.lang.String[] { "Book", });
    internal_static_book_v1_ListBooksResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_book_v1_ListBooksResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_book_v1_ListBooksResponse_descriptor,
        new java.lang.String[] { "Books", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
