// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: author/v1/author.proto
// Protobuf Java Version: 4.31.1

package org.noxhalley.contracts.author.v1;

@com.google.protobuf.Generated
public final class AuthorOuterClass {
  private AuthorOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      AuthorOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AuthorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:author.v1.Author)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 age = 3 [json_name = "age"];</code>
     * @return The age.
     */
    int getAge();
  }
  /**
   * Protobuf type {@code author.v1.Author}
   */
  public static final class Author extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:author.v1.Author)
      AuthorOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        Author.class.getName());
    }
    // Use Author.newBuilder() to construct.
    private Author(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Author() {
      name_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.noxhalley.contracts.author.v1.AuthorOuterClass.internal_static_author_v1_Author_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.noxhalley.contracts.author.v1.AuthorOuterClass.internal_static_author_v1_Author_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.noxhalley.contracts.author.v1.AuthorOuterClass.Author.class, org.noxhalley.contracts.author.v1.AuthorOuterClass.Author.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 3;
    private int age_ = 0;
    /**
     * <code>int32 age = 3 [json_name = "age"];</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
      }
      if (age_ != 0) {
        output.writeInt32(3, age_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, age_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.noxhalley.contracts.author.v1.AuthorOuterClass.Author)) {
        return super.equals(obj);
      }
      org.noxhalley.contracts.author.v1.AuthorOuterClass.Author other = (org.noxhalley.contracts.author.v1.AuthorOuterClass.Author) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getAge()
          != other.getAge()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.Author parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.Author parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.Author parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.Author parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.Author parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.Author parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.Author parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.Author parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.Author parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.Author parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.Author parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.Author parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.noxhalley.contracts.author.v1.AuthorOuterClass.Author prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code author.v1.Author}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:author.v1.Author)
        org.noxhalley.contracts.author.v1.AuthorOuterClass.AuthorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.noxhalley.contracts.author.v1.AuthorOuterClass.internal_static_author_v1_Author_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.noxhalley.contracts.author.v1.AuthorOuterClass.internal_static_author_v1_Author_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.noxhalley.contracts.author.v1.AuthorOuterClass.Author.class, org.noxhalley.contracts.author.v1.AuthorOuterClass.Author.Builder.class);
      }

      // Construct using org.noxhalley.contracts.author.v1.AuthorOuterClass.Author.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        name_ = "";
        age_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.noxhalley.contracts.author.v1.AuthorOuterClass.internal_static_author_v1_Author_descriptor;
      }

      @java.lang.Override
      public org.noxhalley.contracts.author.v1.AuthorOuterClass.Author getDefaultInstanceForType() {
        return org.noxhalley.contracts.author.v1.AuthorOuterClass.Author.getDefaultInstance();
      }

      @java.lang.Override
      public org.noxhalley.contracts.author.v1.AuthorOuterClass.Author build() {
        org.noxhalley.contracts.author.v1.AuthorOuterClass.Author result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.noxhalley.contracts.author.v1.AuthorOuterClass.Author buildPartial() {
        org.noxhalley.contracts.author.v1.AuthorOuterClass.Author result = new org.noxhalley.contracts.author.v1.AuthorOuterClass.Author(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.noxhalley.contracts.author.v1.AuthorOuterClass.Author result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.age_ = age_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.noxhalley.contracts.author.v1.AuthorOuterClass.Author) {
          return mergeFrom((org.noxhalley.contracts.author.v1.AuthorOuterClass.Author)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.noxhalley.contracts.author.v1.AuthorOuterClass.Author other) {
        if (other == org.noxhalley.contracts.author.v1.AuthorOuterClass.Author.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                age_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1 [json_name = "id"];</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1 [json_name = "id"];</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1 [json_name = "id"];</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2 [json_name = "name"];</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2 [json_name = "name"];</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2 [json_name = "name"];</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2 [json_name = "name"];</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2 [json_name = "name"];</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 3 [json_name = "age"];</code>
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 3 [json_name = "age"];</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {

        age_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 3 [json_name = "age"];</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000004);
        age_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:author.v1.Author)
    }

    // @@protoc_insertion_point(class_scope:author.v1.Author)
    private static final org.noxhalley.contracts.author.v1.AuthorOuterClass.Author DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.noxhalley.contracts.author.v1.AuthorOuterClass.Author();
    }

    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.Author getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Author>
        PARSER = new com.google.protobuf.AbstractParser<Author>() {
      @java.lang.Override
      public Author parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Author> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Author> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.noxhalley.contracts.author.v1.AuthorOuterClass.Author getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetAuthorRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:author.v1.GetAuthorRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    int getId();
  }
  /**
   * Protobuf type {@code author.v1.GetAuthorRequest}
   */
  public static final class GetAuthorRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:author.v1.GetAuthorRequest)
      GetAuthorRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        GetAuthorRequest.class.getName());
    }
    // Use GetAuthorRequest.newBuilder() to construct.
    private GetAuthorRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetAuthorRequest() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.noxhalley.contracts.author.v1.AuthorOuterClass.internal_static_author_v1_GetAuthorRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.noxhalley.contracts.author.v1.AuthorOuterClass.internal_static_author_v1_GetAuthorRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest.class, org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest)) {
        return super.equals(obj);
      }
      org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest other = (org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest) obj;

      if (getId()
          != other.getId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code author.v1.GetAuthorRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:author.v1.GetAuthorRequest)
        org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.noxhalley.contracts.author.v1.AuthorOuterClass.internal_static_author_v1_GetAuthorRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.noxhalley.contracts.author.v1.AuthorOuterClass.internal_static_author_v1_GetAuthorRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest.class, org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest.Builder.class);
      }

      // Construct using org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.noxhalley.contracts.author.v1.AuthorOuterClass.internal_static_author_v1_GetAuthorRequest_descriptor;
      }

      @java.lang.Override
      public org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest getDefaultInstanceForType() {
        return org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest build() {
        org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest buildPartial() {
        org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest result = new org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest) {
          return mergeFrom((org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest other) {
        if (other == org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1 [json_name = "id"];</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1 [json_name = "id"];</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1 [json_name = "id"];</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:author.v1.GetAuthorRequest)
    }

    // @@protoc_insertion_point(class_scope:author.v1.GetAuthorRequest)
    private static final org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest();
    }

    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetAuthorRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetAuthorRequest>() {
      @java.lang.Override
      public GetAuthorRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetAuthorRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetAuthorRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetAuthorResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:author.v1.GetAuthorResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.author.v1.Author author = 1 [json_name = "author"];</code>
     * @return Whether the author field is set.
     */
    boolean hasAuthor();
    /**
     * <code>.author.v1.Author author = 1 [json_name = "author"];</code>
     * @return The author.
     */
    org.noxhalley.contracts.author.v1.AuthorOuterClass.Author getAuthor();
    /**
     * <code>.author.v1.Author author = 1 [json_name = "author"];</code>
     */
    org.noxhalley.contracts.author.v1.AuthorOuterClass.AuthorOrBuilder getAuthorOrBuilder();
  }
  /**
   * Protobuf type {@code author.v1.GetAuthorResponse}
   */
  public static final class GetAuthorResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:author.v1.GetAuthorResponse)
      GetAuthorResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        GetAuthorResponse.class.getName());
    }
    // Use GetAuthorResponse.newBuilder() to construct.
    private GetAuthorResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetAuthorResponse() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.noxhalley.contracts.author.v1.AuthorOuterClass.internal_static_author_v1_GetAuthorResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.noxhalley.contracts.author.v1.AuthorOuterClass.internal_static_author_v1_GetAuthorResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse.class, org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse.Builder.class);
    }

    private int bitField0_;
    public static final int AUTHOR_FIELD_NUMBER = 1;
    private org.noxhalley.contracts.author.v1.AuthorOuterClass.Author author_;
    /**
     * <code>.author.v1.Author author = 1 [json_name = "author"];</code>
     * @return Whether the author field is set.
     */
    @java.lang.Override
    public boolean hasAuthor() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.author.v1.Author author = 1 [json_name = "author"];</code>
     * @return The author.
     */
    @java.lang.Override
    public org.noxhalley.contracts.author.v1.AuthorOuterClass.Author getAuthor() {
      return author_ == null ? org.noxhalley.contracts.author.v1.AuthorOuterClass.Author.getDefaultInstance() : author_;
    }
    /**
     * <code>.author.v1.Author author = 1 [json_name = "author"];</code>
     */
    @java.lang.Override
    public org.noxhalley.contracts.author.v1.AuthorOuterClass.AuthorOrBuilder getAuthorOrBuilder() {
      return author_ == null ? org.noxhalley.contracts.author.v1.AuthorOuterClass.Author.getDefaultInstance() : author_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getAuthor());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getAuthor());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse)) {
        return super.equals(obj);
      }
      org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse other = (org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse) obj;

      if (hasAuthor() != other.hasAuthor()) return false;
      if (hasAuthor()) {
        if (!getAuthor()
            .equals(other.getAuthor())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAuthor()) {
        hash = (37 * hash) + AUTHOR_FIELD_NUMBER;
        hash = (53 * hash) + getAuthor().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code author.v1.GetAuthorResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:author.v1.GetAuthorResponse)
        org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.noxhalley.contracts.author.v1.AuthorOuterClass.internal_static_author_v1_GetAuthorResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.noxhalley.contracts.author.v1.AuthorOuterClass.internal_static_author_v1_GetAuthorResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse.class, org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse.Builder.class);
      }

      // Construct using org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetAuthorFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        author_ = null;
        if (authorBuilder_ != null) {
          authorBuilder_.dispose();
          authorBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.noxhalley.contracts.author.v1.AuthorOuterClass.internal_static_author_v1_GetAuthorResponse_descriptor;
      }

      @java.lang.Override
      public org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse getDefaultInstanceForType() {
        return org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse build() {
        org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse buildPartial() {
        org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse result = new org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.author_ = authorBuilder_ == null
              ? author_
              : authorBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse) {
          return mergeFrom((org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse other) {
        if (other == org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse.getDefaultInstance()) return this;
        if (other.hasAuthor()) {
          mergeAuthor(other.getAuthor());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    internalGetAuthorFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private org.noxhalley.contracts.author.v1.AuthorOuterClass.Author author_;
      private com.google.protobuf.SingleFieldBuilder<
          org.noxhalley.contracts.author.v1.AuthorOuterClass.Author, org.noxhalley.contracts.author.v1.AuthorOuterClass.Author.Builder, org.noxhalley.contracts.author.v1.AuthorOuterClass.AuthorOrBuilder> authorBuilder_;
      /**
       * <code>.author.v1.Author author = 1 [json_name = "author"];</code>
       * @return Whether the author field is set.
       */
      public boolean hasAuthor() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.author.v1.Author author = 1 [json_name = "author"];</code>
       * @return The author.
       */
      public org.noxhalley.contracts.author.v1.AuthorOuterClass.Author getAuthor() {
        if (authorBuilder_ == null) {
          return author_ == null ? org.noxhalley.contracts.author.v1.AuthorOuterClass.Author.getDefaultInstance() : author_;
        } else {
          return authorBuilder_.getMessage();
        }
      }
      /**
       * <code>.author.v1.Author author = 1 [json_name = "author"];</code>
       */
      public Builder setAuthor(org.noxhalley.contracts.author.v1.AuthorOuterClass.Author value) {
        if (authorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          author_ = value;
        } else {
          authorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.author.v1.Author author = 1 [json_name = "author"];</code>
       */
      public Builder setAuthor(
          org.noxhalley.contracts.author.v1.AuthorOuterClass.Author.Builder builderForValue) {
        if (authorBuilder_ == null) {
          author_ = builderForValue.build();
        } else {
          authorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.author.v1.Author author = 1 [json_name = "author"];</code>
       */
      public Builder mergeAuthor(org.noxhalley.contracts.author.v1.AuthorOuterClass.Author value) {
        if (authorBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            author_ != null &&
            author_ != org.noxhalley.contracts.author.v1.AuthorOuterClass.Author.getDefaultInstance()) {
            getAuthorBuilder().mergeFrom(value);
          } else {
            author_ = value;
          }
        } else {
          authorBuilder_.mergeFrom(value);
        }
        if (author_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.author.v1.Author author = 1 [json_name = "author"];</code>
       */
      public Builder clearAuthor() {
        bitField0_ = (bitField0_ & ~0x00000001);
        author_ = null;
        if (authorBuilder_ != null) {
          authorBuilder_.dispose();
          authorBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.author.v1.Author author = 1 [json_name = "author"];</code>
       */
      public org.noxhalley.contracts.author.v1.AuthorOuterClass.Author.Builder getAuthorBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return internalGetAuthorFieldBuilder().getBuilder();
      }
      /**
       * <code>.author.v1.Author author = 1 [json_name = "author"];</code>
       */
      public org.noxhalley.contracts.author.v1.AuthorOuterClass.AuthorOrBuilder getAuthorOrBuilder() {
        if (authorBuilder_ != null) {
          return authorBuilder_.getMessageOrBuilder();
        } else {
          return author_ == null ?
              org.noxhalley.contracts.author.v1.AuthorOuterClass.Author.getDefaultInstance() : author_;
        }
      }
      /**
       * <code>.author.v1.Author author = 1 [json_name = "author"];</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.noxhalley.contracts.author.v1.AuthorOuterClass.Author, org.noxhalley.contracts.author.v1.AuthorOuterClass.Author.Builder, org.noxhalley.contracts.author.v1.AuthorOuterClass.AuthorOrBuilder> 
          internalGetAuthorFieldBuilder() {
        if (authorBuilder_ == null) {
          authorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.noxhalley.contracts.author.v1.AuthorOuterClass.Author, org.noxhalley.contracts.author.v1.AuthorOuterClass.Author.Builder, org.noxhalley.contracts.author.v1.AuthorOuterClass.AuthorOrBuilder>(
                  getAuthor(),
                  getParentForChildren(),
                  isClean());
          author_ = null;
        }
        return authorBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:author.v1.GetAuthorResponse)
    }

    // @@protoc_insertion_point(class_scope:author.v1.GetAuthorResponse)
    private static final org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse();
    }

    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetAuthorResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetAuthorResponse>() {
      @java.lang.Override
      public GetAuthorResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetAuthorResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetAuthorResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.noxhalley.contracts.author.v1.AuthorOuterClass.GetAuthorResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ListAuthorsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:author.v1.ListAuthorsResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .author.v1.Author authors = 1 [json_name = "authors"];</code>
     */
    java.util.List<org.noxhalley.contracts.author.v1.AuthorOuterClass.Author> 
        getAuthorsList();
    /**
     * <code>repeated .author.v1.Author authors = 1 [json_name = "authors"];</code>
     */
    org.noxhalley.contracts.author.v1.AuthorOuterClass.Author getAuthors(int index);
    /**
     * <code>repeated .author.v1.Author authors = 1 [json_name = "authors"];</code>
     */
    int getAuthorsCount();
    /**
     * <code>repeated .author.v1.Author authors = 1 [json_name = "authors"];</code>
     */
    java.util.List<? extends org.noxhalley.contracts.author.v1.AuthorOuterClass.AuthorOrBuilder> 
        getAuthorsOrBuilderList();
    /**
     * <code>repeated .author.v1.Author authors = 1 [json_name = "authors"];</code>
     */
    org.noxhalley.contracts.author.v1.AuthorOuterClass.AuthorOrBuilder getAuthorsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code author.v1.ListAuthorsResponse}
   */
  public static final class ListAuthorsResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:author.v1.ListAuthorsResponse)
      ListAuthorsResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        ListAuthorsResponse.class.getName());
    }
    // Use ListAuthorsResponse.newBuilder() to construct.
    private ListAuthorsResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ListAuthorsResponse() {
      authors_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.noxhalley.contracts.author.v1.AuthorOuterClass.internal_static_author_v1_ListAuthorsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.noxhalley.contracts.author.v1.AuthorOuterClass.internal_static_author_v1_ListAuthorsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse.class, org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse.Builder.class);
    }

    public static final int AUTHORS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<org.noxhalley.contracts.author.v1.AuthorOuterClass.Author> authors_;
    /**
     * <code>repeated .author.v1.Author authors = 1 [json_name = "authors"];</code>
     */
    @java.lang.Override
    public java.util.List<org.noxhalley.contracts.author.v1.AuthorOuterClass.Author> getAuthorsList() {
      return authors_;
    }
    /**
     * <code>repeated .author.v1.Author authors = 1 [json_name = "authors"];</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.noxhalley.contracts.author.v1.AuthorOuterClass.AuthorOrBuilder> 
        getAuthorsOrBuilderList() {
      return authors_;
    }
    /**
     * <code>repeated .author.v1.Author authors = 1 [json_name = "authors"];</code>
     */
    @java.lang.Override
    public int getAuthorsCount() {
      return authors_.size();
    }
    /**
     * <code>repeated .author.v1.Author authors = 1 [json_name = "authors"];</code>
     */
    @java.lang.Override
    public org.noxhalley.contracts.author.v1.AuthorOuterClass.Author getAuthors(int index) {
      return authors_.get(index);
    }
    /**
     * <code>repeated .author.v1.Author authors = 1 [json_name = "authors"];</code>
     */
    @java.lang.Override
    public org.noxhalley.contracts.author.v1.AuthorOuterClass.AuthorOrBuilder getAuthorsOrBuilder(
        int index) {
      return authors_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < authors_.size(); i++) {
        output.writeMessage(1, authors_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < authors_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, authors_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse)) {
        return super.equals(obj);
      }
      org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse other = (org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse) obj;

      if (!getAuthorsList()
          .equals(other.getAuthorsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getAuthorsCount() > 0) {
        hash = (37 * hash) + AUTHORS_FIELD_NUMBER;
        hash = (53 * hash) + getAuthorsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code author.v1.ListAuthorsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:author.v1.ListAuthorsResponse)
        org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.noxhalley.contracts.author.v1.AuthorOuterClass.internal_static_author_v1_ListAuthorsResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.noxhalley.contracts.author.v1.AuthorOuterClass.internal_static_author_v1_ListAuthorsResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse.class, org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse.Builder.class);
      }

      // Construct using org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (authorsBuilder_ == null) {
          authors_ = java.util.Collections.emptyList();
        } else {
          authors_ = null;
          authorsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.noxhalley.contracts.author.v1.AuthorOuterClass.internal_static_author_v1_ListAuthorsResponse_descriptor;
      }

      @java.lang.Override
      public org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse getDefaultInstanceForType() {
        return org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse build() {
        org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse buildPartial() {
        org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse result = new org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse result) {
        if (authorsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            authors_ = java.util.Collections.unmodifiableList(authors_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.authors_ = authors_;
        } else {
          result.authors_ = authorsBuilder_.build();
        }
      }

      private void buildPartial0(org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse) {
          return mergeFrom((org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse other) {
        if (other == org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse.getDefaultInstance()) return this;
        if (authorsBuilder_ == null) {
          if (!other.authors_.isEmpty()) {
            if (authors_.isEmpty()) {
              authors_ = other.authors_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAuthorsIsMutable();
              authors_.addAll(other.authors_);
            }
            onChanged();
          }
        } else {
          if (!other.authors_.isEmpty()) {
            if (authorsBuilder_.isEmpty()) {
              authorsBuilder_.dispose();
              authorsBuilder_ = null;
              authors_ = other.authors_;
              bitField0_ = (bitField0_ & ~0x00000001);
              authorsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetAuthorsFieldBuilder() : null;
            } else {
              authorsBuilder_.addAllMessages(other.authors_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                org.noxhalley.contracts.author.v1.AuthorOuterClass.Author m =
                    input.readMessage(
                        org.noxhalley.contracts.author.v1.AuthorOuterClass.Author.parser(),
                        extensionRegistry);
                if (authorsBuilder_ == null) {
                  ensureAuthorsIsMutable();
                  authors_.add(m);
                } else {
                  authorsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<org.noxhalley.contracts.author.v1.AuthorOuterClass.Author> authors_ =
        java.util.Collections.emptyList();
      private void ensureAuthorsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          authors_ = new java.util.ArrayList<org.noxhalley.contracts.author.v1.AuthorOuterClass.Author>(authors_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.noxhalley.contracts.author.v1.AuthorOuterClass.Author, org.noxhalley.contracts.author.v1.AuthorOuterClass.Author.Builder, org.noxhalley.contracts.author.v1.AuthorOuterClass.AuthorOrBuilder> authorsBuilder_;

      /**
       * <code>repeated .author.v1.Author authors = 1 [json_name = "authors"];</code>
       */
      public java.util.List<org.noxhalley.contracts.author.v1.AuthorOuterClass.Author> getAuthorsList() {
        if (authorsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(authors_);
        } else {
          return authorsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .author.v1.Author authors = 1 [json_name = "authors"];</code>
       */
      public int getAuthorsCount() {
        if (authorsBuilder_ == null) {
          return authors_.size();
        } else {
          return authorsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .author.v1.Author authors = 1 [json_name = "authors"];</code>
       */
      public org.noxhalley.contracts.author.v1.AuthorOuterClass.Author getAuthors(int index) {
        if (authorsBuilder_ == null) {
          return authors_.get(index);
        } else {
          return authorsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .author.v1.Author authors = 1 [json_name = "authors"];</code>
       */
      public Builder setAuthors(
          int index, org.noxhalley.contracts.author.v1.AuthorOuterClass.Author value) {
        if (authorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAuthorsIsMutable();
          authors_.set(index, value);
          onChanged();
        } else {
          authorsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .author.v1.Author authors = 1 [json_name = "authors"];</code>
       */
      public Builder setAuthors(
          int index, org.noxhalley.contracts.author.v1.AuthorOuterClass.Author.Builder builderForValue) {
        if (authorsBuilder_ == null) {
          ensureAuthorsIsMutable();
          authors_.set(index, builderForValue.build());
          onChanged();
        } else {
          authorsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .author.v1.Author authors = 1 [json_name = "authors"];</code>
       */
      public Builder addAuthors(org.noxhalley.contracts.author.v1.AuthorOuterClass.Author value) {
        if (authorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAuthorsIsMutable();
          authors_.add(value);
          onChanged();
        } else {
          authorsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .author.v1.Author authors = 1 [json_name = "authors"];</code>
       */
      public Builder addAuthors(
          int index, org.noxhalley.contracts.author.v1.AuthorOuterClass.Author value) {
        if (authorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAuthorsIsMutable();
          authors_.add(index, value);
          onChanged();
        } else {
          authorsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .author.v1.Author authors = 1 [json_name = "authors"];</code>
       */
      public Builder addAuthors(
          org.noxhalley.contracts.author.v1.AuthorOuterClass.Author.Builder builderForValue) {
        if (authorsBuilder_ == null) {
          ensureAuthorsIsMutable();
          authors_.add(builderForValue.build());
          onChanged();
        } else {
          authorsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .author.v1.Author authors = 1 [json_name = "authors"];</code>
       */
      public Builder addAuthors(
          int index, org.noxhalley.contracts.author.v1.AuthorOuterClass.Author.Builder builderForValue) {
        if (authorsBuilder_ == null) {
          ensureAuthorsIsMutable();
          authors_.add(index, builderForValue.build());
          onChanged();
        } else {
          authorsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .author.v1.Author authors = 1 [json_name = "authors"];</code>
       */
      public Builder addAllAuthors(
          java.lang.Iterable<? extends org.noxhalley.contracts.author.v1.AuthorOuterClass.Author> values) {
        if (authorsBuilder_ == null) {
          ensureAuthorsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, authors_);
          onChanged();
        } else {
          authorsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .author.v1.Author authors = 1 [json_name = "authors"];</code>
       */
      public Builder clearAuthors() {
        if (authorsBuilder_ == null) {
          authors_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          authorsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .author.v1.Author authors = 1 [json_name = "authors"];</code>
       */
      public Builder removeAuthors(int index) {
        if (authorsBuilder_ == null) {
          ensureAuthorsIsMutable();
          authors_.remove(index);
          onChanged();
        } else {
          authorsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .author.v1.Author authors = 1 [json_name = "authors"];</code>
       */
      public org.noxhalley.contracts.author.v1.AuthorOuterClass.Author.Builder getAuthorsBuilder(
          int index) {
        return internalGetAuthorsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .author.v1.Author authors = 1 [json_name = "authors"];</code>
       */
      public org.noxhalley.contracts.author.v1.AuthorOuterClass.AuthorOrBuilder getAuthorsOrBuilder(
          int index) {
        if (authorsBuilder_ == null) {
          return authors_.get(index);  } else {
          return authorsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .author.v1.Author authors = 1 [json_name = "authors"];</code>
       */
      public java.util.List<? extends org.noxhalley.contracts.author.v1.AuthorOuterClass.AuthorOrBuilder> 
           getAuthorsOrBuilderList() {
        if (authorsBuilder_ != null) {
          return authorsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(authors_);
        }
      }
      /**
       * <code>repeated .author.v1.Author authors = 1 [json_name = "authors"];</code>
       */
      public org.noxhalley.contracts.author.v1.AuthorOuterClass.Author.Builder addAuthorsBuilder() {
        return internalGetAuthorsFieldBuilder().addBuilder(
            org.noxhalley.contracts.author.v1.AuthorOuterClass.Author.getDefaultInstance());
      }
      /**
       * <code>repeated .author.v1.Author authors = 1 [json_name = "authors"];</code>
       */
      public org.noxhalley.contracts.author.v1.AuthorOuterClass.Author.Builder addAuthorsBuilder(
          int index) {
        return internalGetAuthorsFieldBuilder().addBuilder(
            index, org.noxhalley.contracts.author.v1.AuthorOuterClass.Author.getDefaultInstance());
      }
      /**
       * <code>repeated .author.v1.Author authors = 1 [json_name = "authors"];</code>
       */
      public java.util.List<org.noxhalley.contracts.author.v1.AuthorOuterClass.Author.Builder> 
           getAuthorsBuilderList() {
        return internalGetAuthorsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.noxhalley.contracts.author.v1.AuthorOuterClass.Author, org.noxhalley.contracts.author.v1.AuthorOuterClass.Author.Builder, org.noxhalley.contracts.author.v1.AuthorOuterClass.AuthorOrBuilder> 
          internalGetAuthorsFieldBuilder() {
        if (authorsBuilder_ == null) {
          authorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.noxhalley.contracts.author.v1.AuthorOuterClass.Author, org.noxhalley.contracts.author.v1.AuthorOuterClass.Author.Builder, org.noxhalley.contracts.author.v1.AuthorOuterClass.AuthorOrBuilder>(
                  authors_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          authors_ = null;
        }
        return authorsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:author.v1.ListAuthorsResponse)
    }

    // @@protoc_insertion_point(class_scope:author.v1.ListAuthorsResponse)
    private static final org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse();
    }

    public static org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ListAuthorsResponse>
        PARSER = new com.google.protobuf.AbstractParser<ListAuthorsResponse>() {
      @java.lang.Override
      public ListAuthorsResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ListAuthorsResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ListAuthorsResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.noxhalley.contracts.author.v1.AuthorOuterClass.ListAuthorsResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_author_v1_Author_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_author_v1_Author_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_author_v1_GetAuthorRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_author_v1_GetAuthorRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_author_v1_GetAuthorResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_author_v1_GetAuthorResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_author_v1_ListAuthorsResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_author_v1_ListAuthorsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026author/v1/author.proto\022\tauthor.v1\032\033goo" +
      "gle/protobuf/empty.proto\">\n\006Author\022\016\n\002id" +
      "\030\001 \001(\005R\002id\022\022\n\004name\030\002 \001(\tR\004name\022\020\n\003age\030\003 " +
      "\001(\005R\003age\"\"\n\020GetAuthorRequest\022\016\n\002id\030\001 \001(\005" +
      "R\002id\">\n\021GetAuthorResponse\022)\n\006author\030\001 \001(" +
      "\0132\021.author.v1.AuthorR\006author\"B\n\023ListAuth" +
      "orsResponse\022+\n\007authors\030\001 \003(\0132\021.author.v1" +
      ".AuthorR\007authors2\242\001\n\rAuthorService\022H\n\tGe" +
      "tAuthor\022\033.author.v1.GetAuthorRequest\032\034.a" +
      "uthor.v1.GetAuthorResponse\"\000\022G\n\013ListAuth" +
      "ors\022\026.google.protobuf.Empty\032\036.author.v1." +
      "ListAuthorsResponse\"\000B]\n!org.noxhalley.c" +
      "ontracts.author.v1Z8github.com/noxhalley" +
      "/contracts/gen/go/author/v1;authorv1b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_author_v1_Author_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_author_v1_Author_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_author_v1_Author_descriptor,
        new java.lang.String[] { "Id", "Name", "Age", });
    internal_static_author_v1_GetAuthorRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_author_v1_GetAuthorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_author_v1_GetAuthorRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_author_v1_GetAuthorResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_author_v1_GetAuthorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_author_v1_GetAuthorResponse_descriptor,
        new java.lang.String[] { "Author", });
    internal_static_author_v1_ListAuthorsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_author_v1_ListAuthorsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_author_v1_ListAuthorsResponse_descriptor,
        new java.lang.String[] { "Authors", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
